Layout/EndOfLine:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

MultilineTernaryOperator:
  Exclude:
  - 'app/controllers/devise/registrations_controller.rb'

Layout/EmptyLinesAroundBlockBody:
  Exclude:
  - 'db/schema.rb'

Style/NumericLiterals:
  Exclude:
  - 'db/schema.rb'

Style/StringLiterals:
  Exclude:
  - 'db/schema.rb'

Style/WordArray:
  Exclude:
  - 'db/schema.rb'

Lint/ScriptPermission:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/MixinUsage:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/LineLength:
  Max: 120
  Exclude:
  - 'db/schema.rb'
  IgnoredPatterns:
    - '#.'
