language: ruby

rvm:
- 2.3.3

script:
- rvm gemset use global
- bundle install
- gem list | grep fileutils
- gem uninstall fileutils
- gem update fileutils
- gem list | grep fileutils
- rake db:create
- rake db:migrale

