language: ruby

rvm:
- 2.3.3

services:
- postgresql

script:
- bundle install
- psql -c "create user alex with encrypted password 'qwerty123';" -U postgres
- bundle exec rake db:create
- bundle exec rake db:migrale

