version: '3.0'
services:
  #elasticsearch:
  #  image: docker.elastic.co/elasticsearch/elasticsearch:6.2.1
  #  ports:
  #    - 9200:9200
  #    - 9300:9300
  #  ulimits:
  #    memlock:
  #      soft: -1
  #      hard: -1
  #  volumes:
  #    - ./docker_data/elasticsearch/data:/usr/share/elasticsearch/data
  #  environment:
  #    - cluster.name=docker-cluster
  #    - bootstrap.memory_lock=true
  #    - xpack.security.enabled=false
  #    - xpack.monitoring.enabled=false
  #    - xpack.graph.enabled=false
  #    - xpack.watcher.enabled=false
  #    - cluster.routing.allocation.enable=all
  #
  db:
    image: postgres:10
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${DB_USER_PASSWORD}

  webpacker:
    image: ${DOCKER_IMAGE_NAME-dockerrailsdemo}
    command: ["./scripts/start_webpack_dev.sh"]
    volumes:
      - .:/opt/dockerrailsdemo:cached
    ports:
      - 3035:3035

  web:
    image: ${DOCKER_IMAGE_NAME-dockerrailsdemo}
    build:
      context: .
      args:
        precompileassets: 'not'
    links:
      - db
      - webpacker
    #  - elasticsearch
    ports:
      - 3000:3000
    command: ["./scripts/wait-for-it.sh", "db:5432", "--", "./scripts/start_rails.sh"]
    volumes:
      - .:/opt/dockerrailsdemo:cached
